### ISSUE TITLE
Can't run examples (undefined clu:setup)

### ISSUE THREAD

**Issue by mrluc** [tonyrog/cl#26]
Running `rebar compile` seems to work, and I ensure that $ERL_LIBS is set to the `cl` folder:

```
$ echo $ERL_LIBS
/Users/mrluc/projects/mine/elixir/cl/

 $ rebar compile
 ==> cl (compile)
```

Then, entering the `examples/` directory and type `make`, and again it seems to work:

```
$ make
erlc -W -pa ../../cl/ebin -o . cl_basic.erl
erlc -W -pa ../../cl/ebin -o . cl_square_float.erl
erlc -W -pa ../../cl/ebin -o . cl_map.erl
erlc -W -pa ../../cl/ebin -o . cl_binary_test.erl
erlc -W -pa ../../cl/ebin -o . cl_bandwidth.erl
erlc -W -pa ../../cl/ebin -o . cl_mul.erl
erlc -W -pa ../../cl/ebin -o . cl_test.erl
erlc -W -pa ../../cl/ebin -o . cl_buffer.erl
erlc -W -pa ../../cl/ebin -o . cl_image.erl
erlc -W -pa ../../cl/ebin -o . cl_compile.erl
```

However, as there's no guidance on how to run the examples, I tried first the following:

```
$ erl -s cl_basic
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

{"init terminating in do_boot",{undef,[{cl_basic,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

Okay, undefined `cl_basic:start`; after peaking inside the sources, tried this:

```
$ erl -s cl_basic test
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

{"init terminating in do_boot",{undef,[{clu,setup,[all],[]},{cl_basic,test,1,[{file,"cl_basic.erl"},{line,13}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

Which seems to be a bona fide error -- it can't find `clu:setup`, ie the example doesn't seem to be finding/using the `../../cl/ebin` files despite me explicitly setting the `ERL_LIBS` env var as mentioned in Readme.

Any thoughts on what I'm missing?

**Comment by tonyrog** [comment]
You need to set path correct, either with -pa or set ERL_LIBS (note the S in LIBS) one level up.

erl -pa ~/path_to_/cl/ebin -s cl_basic test

or run examples from erlang prompt
erl -pa ~/path_to/cl/ebin -s
> cl_basic:test().
